package org.brms.myproject;
rule "Check whether the type of Construction is masonary"
    when
        WallConstruction(wallConstruction=="Masonry")
    then
        System.out.println("Wall construction is masonry");
end

rule "Check whether the type of Construction is Frame"
    when
        WallConstruction(wallConstruction=="Frame")
    then
        System.out.println("Wall construction is Frame");
end

rule "Check the type of Construction of Mixed-masonary"
    when
        WallConstruction(wallConstruction=="Mixed-Masonry-Frame")
    then
        System.out.println("Wall construction is Mixed-masonry");
end
